choir/member/urls.py
from django.conf.urls.defaults import patterns, url
from choir.member.forms import MassMailForm, MassMailPreviewForm
from choir.member.views import MemberListView

urlpatterns = patterns("",
    url(r'^$', MemberListView.as_view(
        [MassMailForm, MassMailPreviewForm]), name='member_list'),
)

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('events/', include(('choir.events.urls', 'events'), namespace='events')),
    path('repertory/', include(('choir.repertory.urls', 'repertory'), namespace='repertory')),
    path('player/', include(('choir.player.urls', 'player'), namespace='player')),
    path('', RedirectView.as_view(pattern_name='repertory:song_list'), name='home'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Debug toolbar
if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

choir/member/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext as _


class Role(models.Model):
    name = models.CharField(_('name'), max_length=200, unique=True)
    order = models.PositiveIntegerField(_('order'), null=True, blank=True)

    class Meta:
        verbose_name = _('role')
        verbose_name_plural = _('roles')
        ordering = ('order', 'name',)

    def __unicode__(self):
        return unicode(self.name)

    def get_members_with_mail(self):
        return Member.objects.filter(role=self).exclude(email='')

    def get_members_without_mail(self):
        return Member.objects.filter(role=self).filter(email='')


class Member(models.Model):
    user = models.ForeignKey(User, null=True, blank=True,
        verbose_name=_('user'))
    surname = models.CharField(_('surname'), max_length=200, blank=True)
    name = models.CharField(_('name'), max_length=200, blank=True)
    nickname = models.CharField(_('nickname'), max_length=200, blank=True)
    role = models.ForeignKey(Role, null=True, blank=True,
        related_name='member_role_pk', verbose_name=_('role'))
    phone_number = models.CharField(_('phone number'), max_length=50,
        blank=True)
    mobile_number = models.CharField(_('mobile number'), max_length=50,
        blank=True)
    email = models.CharField(_('email'), max_length=200, blank=True)
    address = models.CharField(_('address'), max_length=200, blank=True)
    city = models.CharField(_('city'), max_length=200, blank=True)
    province = models.CharField(_('province'), max_length=200, blank=True)
    zip_code = models.CharField(_('zip code'), max_length=50, blank=True)

    class Meta:
        verbose_name = _('member')
        verbose_name_plural = _('members')
        ordering = ('role', 'surname', 'name')

    def __unicode__(self):
        if self.nickname:
            return u'%s (%s)' % (self.nickname, self.get_full_name())
        return self.get_full_name()
    __unicode__.short_description = _('member')
    __unicode__.admin_order_field = 'surname'
    __unicode__.allow_tags = False

    def get_absolute_url(self):
        return reverse('member:member_list')

    def get_admin_url(self):
        return reverse('admin:member_member_change', args=[self.pk])

    def get_full_name(self):
        return u'%s %s'.strip() % (self.name, self.surname)

    def get_phone_numbers(self):
        numbers = []
        if self.phone_number:
            numbers.append(self.phone_number)
        if self.mobile_number:
            numbers.append(self.mobile_number)
        return numbers

choir/member/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _
from choir.member import models


class MemberForm(forms.ModelForm):
    class Meta:
        model = models.Member
        widgets = dict(
            surname=forms.TextInput(attrs=dict(size=20)),
            name=forms.TextInput(attrs=dict(size=20)),
            phone_number=forms.TextInput(attrs=dict(size=15)),
            mobile_number=forms.TextInput(attrs=dict(size=15)),
            nickname=forms.TextInput(attrs=dict(size=10)),
            address=forms.TextInput(attrs=dict(size=30)),
            city=forms.TextInput(attrs=dict(size=30)),
            province=forms.TextInput(attrs=dict(size=2)),
            zip_code=forms.TextInput(attrs=dict(size=5)),
        )

    def clean_surname(self):
        value = self.cleaned_data['surname']
        user = self.cleaned_data.get('user', None)
        if user and not value:
            value = user.last_name
        if not value:
            raise ValidationError(_(u'This field is required.'))
        return value

    def clean_name(self):
        value = self.cleaned_data['name']
        user = self.cleaned_data.get('user', None)
        if user and not value:
            value = user.first_name
        return value

    def clean_email(self):
        value = self.cleaned_data['email']
        user = self.cleaned_data.get('user', None)
        if user and not value:
            value = user.email
        return value


class MassMailForm(forms.Form):
    roles = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        super(MassMailForm, self).__init__(*args, **kwargs)
        choices = [(x.id, x.name) for x in models.Role.objects.all()]
        choices.insert(0, (0, 'Tutti'))
        self.fields['roles'].choices = choices


class MassMailPreviewForm(forms.Form):
    pass

choir/member/views.py
from django.contrib.formtools.wizard.views import SessionWizardView
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView
from choir.member.models import Role, Member


class MemberListView(SessionWizardView, ListView):
    model = Member
    queryset = Member.objects.all().order_by('role', 'surname', 'name')
    paginate_by = 100

    def done(self, form_list, **kwargs):
        return HttpResponseRedirect(reverse('member:member_list'))

    def get_template_names(self, *args, **kwargs):
        templates = dict()
        templates['0'] = ['member/member_list.html']
        templates['1'] = ['member/mass_mail_preview.html']
        return templates[self.steps.current]

    def get_context_data(self, **kwargs):
        context = ListView.get_context_data(self, object_list=self.get_queryset())
        context.update(super(MemberListView, self).get_context_data(**kwargs))
        if self.steps.current == '1':
            roles = self.get_all_cleaned_data()['roles']
            if '0' in roles:
                context['roles'] = Role.objects.all()
                members = Member.objects.all()
            else:
                context['roles'] = Role.objects.filter(pk__in=roles)
                members = Member.objects.filter(role__in=roles)
            recipients = ['%s <%s>' % (x.get_full_name(), x.email) for x in members if x.email]
            recipients_short = ['%s' % x.email for x in members if x.email]
            context['mail_recipient'] = ', '.join(recipients)
            context['mail_recipient_short'] = '; '.join(recipients_short)
            context['members'] = members
        return context

choir/member/templates/member/mass_mail_preview.html
{% extends "site_base.html" %}
{% load i18n bootstrap_tags %}

{% block head_title %}Mail massiva{% endblock %}

{% block extra_style %}
{{ block.super }}
<style type="text/css">
    table th.centered { text-align: center; }
    table td.centered { text-align: center; }
    table thead th { background-color: #ccf9cc; }
</style>
{% if wizard %}{{ wizard.form.media }}{% endif %}
{% endblock %}

{% block body %}

<div class="page-header">
    <h1>Mail Massiva</h1>
</div>

<div class="row">

{% if perms.member.change_member %}
<div class="span12">

<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>Ruolo</th>
        <th>Con E-mail</th>
        <th>Senza E-mail</th>
    </tr>
    </thead>
    <tbody>
    {% for role in roles %}
    <tr>
        <th>{{ role.name }}</th>
        <td>
            {% for member in role.get_members_with_mail %}
                {{ member.get_full_name }}
             {% if forloop.last %}{% else %} - {% endif %}
            {% endfor %}
        </td>
        <td>
            {% for member in role.get_members_without_mail %}
                {{ member.get_full_name }}
                {% for number in member.get_phone_numbers %}
                    {% if forloop.first %}({% endif %}
                    {{ number }}
                    {% if forloop.last %}){% else %}, {% endif %}
                {% endfor %}
                {% if forloop.last %}{% else %} - {% endif %}
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<form action="" method="post">{% csrf_token %}
{{ wizard.management_form }}
{{ wizard.form|as_bootstrap }}
<div class="form-actions">
    <button name="wizard_goto_step" class="btn" type="submit" value="{{ wizard.steps.prev }}">{% trans "Previous" %}</button>
    <a href="mailto:{{ mail_recipient_short }}" class="btn"><i class="icon-envelope icon-white"></i> Outlook</a>
    <a href="mailto:{{ mail_recipient }}" class="btn btn-primary"><i class="icon-envelope icon-white"></i> E-Mail</a>
</div>
</form>

</div>
{% endif %}

</div>


{% endblock %}

choir/member/templates/member/member_list.html
{% extends "site_base.html" %}
{% load i18n bootstrap_tags %}

{% block head_title %}Membri{% endblock %}

{% block extra_style %}
{{ block.super }}
<style type="text/css">
    table th.centered { text-align: center; }
    table td.centered { text-align: center; }
    table thead th { background-color: #ccf9cc; }
</style>
{% if wizard %}{{ wizard.form.media }}{% endif %}
{% endblock %}

{% block body %}

<div class="page-header">
    <h1>Membri</h1>
</div>

<div class="row">

<div class="span4">

<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Ruolo</th>
    </tr>
    </thead>
    <tbody>
    {% for member in object_list %}
        <tr>
            <th>
                {% if perms.member.change_member %}
                    <a href="{{ member.get_admin_url }}" rel="tooltip" title="Modifica"><i class="icon-edit icon-black"></i></a>
                    {% if member.email %}
                        <a href="mailto:{{ member.get_full_name }} <{{ member.email }}>" rel="tooltip" title="{{ member.email }}"><i class="icon-envelope icon-black"></i></a>
                    {% else %}
                        <i class="icon-black"></i>
                    {% endif %}
                {% endif %}
                {{ member.get_full_name }}
            </th>
            <td>{{ member.role|default:'' }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</div>

{% if perms.member.change_member %}
{% if wizard %}
<div class="span3">
    <legend>Mail massiva</legend>
    <form action="" method="post">{% csrf_token %}
    {{ wizard.management_form }}
    {{ wizard.form|as_bootstrap }}
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">{% trans "Next" %}</button>
    </div>
    </form>
</div>
{% endif %}
{% endif %}

</div>

{% include "pagination/pagination.html" %}

{% endblock %}