choir/events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    path('', views.EventListView.as_view(), name="event_list"),
    path('<slug:slug>/', views.EventDetailView.as_view(), name="event_detail"),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('events/', include(('choir.events.urls', 'events'), namespace='events')),
    path('repertory/', include(('choir.repertory.urls', 'repertory'), namespace='repertory')),
    path('player/', include(('choir.player.urls', 'player'), namespace='player')),
    path('', RedirectView.as_view(pattern_name='repertory:song_list'), name='home'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Debug toolbar
if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

choir/events/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext as _


EVENT_TYPE = dict(
    rehearsal=_('Rehearsal'),
    live=_('Live'),
    other=_('Other'),
)
EVENT_TYPES = [(k, v) for (k, v) in EVENT_TYPE.items()]
DEFAULT_EVENT_TYPE = 'rehearsal'


class Event(models.Model):
    date = models.DateTimeField(_('date'), null=True, blank=True, db_index=True)
    slug = models.SlugField(_('slug'), max_length=200, unique=True, db_index=True)
    type = models.CharField(_('type'), max_length=20, choices=EVENT_TYPES, default=DEFAULT_EVENT_TYPE)
    name = models.CharField(_('name'), max_length=200, blank=True)
    location = models.CharField(_('location'), max_length=200, blank=True, default=settings.DEFAULT_EVENT_LOCATION)
    notes = models.TextField(_('notes'), blank=True)

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        ordering = ('-date',)

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        if self.date:
            slug = self.date.strftime('%Y-%m-%d')
            if not self.slug.startswith(slug):
                self.slug = slug
                events = Event.objects.filter(date__date=self.date.date())
                if self.pk:
                    events = events.exclude(pk=self.pk)
                if events.exists():
                    self.slug += '-' + str(events.count() + 1)
        else:
            self.slug = str(self.id)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('events:event_detail', kwargs={'slug': self.slug})

    def get_title(self):
        if self.type == 'rehearsal':
            return self.get_type_display()
        else:
            return self.name


class EventSong(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, db_index=True)
    song = models.ForeignKey('repertory.Song', on_delete=models.SET_NULL, blank=True,null=True)
    section = models.CharField(_('section'), max_length=200, blank=True)
    soloist = models.CharField(_('soloist'), max_length=200, blank=True)
    order = models.PositiveIntegerField(_('order'), null=True, blank=True, db_index=True)

    class Meta:
        verbose_name = _('event song')
        verbose_name_plural = _('event songs')
        ordering = ('order',)
        indexes = [
            models.Index(fields=['event', 'order']),
        ]

    def __str__(self):
        return self.song.name if self.song else ''

choir/events/forms.py
from django import forms
from choir.events import models


class EventForm(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = '__all__'
        widgets = dict(
            notes=forms.Textarea(attrs=dict(rows=1)),
        )


class EventSongForm(forms.ModelForm):
    class Meta:
        model = models.EventSong
        fields = '__all__'
        widgets = dict(
            section=forms.TextInput(attrs=dict(style='width: 10rem;')),
            soloist=forms.TextInput(attrs=dict(style='width: 8rem;')),
            order=forms.TextInput(attrs=dict(style='width: 2rem;')),
        )

choir/events/views.py
from django.utils import timezone
from django.views.generic import DetailView, ListView
from choir.events import models
from .constants import CHOIR_SECTION


class EventDetailView(DetailView):
    model = models.Event
    slug_field = 'slug'
    context_object_name = 'event'
    slug_url_kwarg = 'slug'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        event = context['event']
        context['choir_section'] = CHOIR_SECTION
        if event.type == 'rehearsal':
            context['title'] = event.get_type_display()
        else:
            context['title'] = event.name
        return context


class EventListView(ListView):
    model = models.Event

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(date__gte=timezone.now().date()).order_by('date')

choir/events/templates/events/base.html
{% extends "site_base.html" %}
{% load i18n %}

choir/events/templates/events/event_detail.html
{% extends "events/base.html" %}
{% load i18n %}


{% block content %}

{% if perms.events %}
    <a href="{% url 'admin:events_event_change' event.pk %}"><i class="bi bi-pen"></i>{% translate "Edit" %}</a>
{% endif %}

<h1>{{ title }} - {{ event.date|date:"l d F G:i" }}</h1>
<h3>{{ event.location }}</h3>
<p>{{ event.notes }}</p>

<h2>{% translate "Songs" %}</h2>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col" class="centered">{% translate "Section" %}</th>
            <th scope="col" class="centered">{% translate "Number" %}</th>
            <th scope="col" class="centered">{% translate "Page" %}</th>
            <th scope="col" class="centered">{% translate "Name" %}</th>
            <th scope="col" class="centered">{% translate "Score Number" %}</th>
            <th scope="col" class="centered">{% translate "Soloist" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for eventsong in event.eventsong_set.all %}

        <tr>
            <td>{{ eventsong.section }}</td>
            <td>{{ eventsong.song.number | default:"" }}</td>
            <td>{{ eventsong.song.page | default:"" }}</td>
            <td>{{ eventsong.song.name }}</td>
            <td>{{ eventsong.song.number | default:"" }}</td>
            <td>{{ eventsong.soloist }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% for section, section_name in choir_section.items %}
<h2>{{ section_name }}</h2>
<div>{{ title }}</div>
<div>{{ event.date|date:"l d F G:i" }}</div>
<div>{{ event.location }}</div>
<ul>
    {% for eventsong in event.eventsong_set.all %}
    <li>
        <div>{{ eventsong.song.name }}</div>
        {% for file in eventsong.song.songfile_set.all %}
            {% if file.type == 'score' %}
            <div><a href="{{ file.file.url }}">{{ file.file.url }}</a></div>
            {% endif %}
            {% if file.type == section %}
            <div><a href="{{ file.file.url }}">{{ file.file.url }}</a></div>
            {% endif %}
        {% endfor %}
    </li>
    {% endfor %}
</ul>
{% endfor %}

{% endblock %}

choir/events/templates/events/event_list.html
{% extends "events/base.html" %}
{% load i18n %}

{% block content %}
<h1>{% translate "Next events" %}</h1>

<table class="table table-hover">
    <tbody>
        {% for event in event_list %}
        <tr>
            <td>{% if user.is_authenticated %}<a href="{% url 'events:event_detail' event.slug %}">{{ event.get_title }}</a>{% else %}{{ event.get_title }}{% endif %}</td>
            <td>{{ event.date|date:"l d F G:i" }}</td>
            <td>{{ event.location }}</td>
            {% if perms.events %}
                <td><a href="{% url 'admin:events_event_change' event.pk %}"><i class="bi bi-pen"></i>{% translate "Edit" %}</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}