choir/events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    path('', views.EventListView.as_view(), name="event_list"),
    path('<slug:slug>/', views.EventDetailView.as_view(), name="event_detail"),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('events/', include(('choir.events.urls', 'events'), namespace='events')),
    path('repertory/', include(('choir.repertory.urls', 'repertory'), namespace='repertory')),
    path('player/', include(('choir.player.urls', 'player'), namespace='player')),
    path('', RedirectView.as_view(pattern_name='repertory:song_list'), name='home'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Debug toolbar
if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += debug_toolbar.toolbar.debug_toolbar_urls()

choir/web/templates/_footer.html
{% load i18n %}
<div class="legal">
    {% trans "&copy; 2012 Massimiliano Ravelli" %}
</div>

choir/web/templates/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.9.55/css/materialdesignicons.min.css" rel="stylesheet">
    <link href="{% static 'web/css/base.css' %}" rel="stylesheet">
    {% block extra_head %}{% endblock %}
    <title>{% block title %}Coro di S.Antonio{% endblock %}</title>
    {% endblock %}
</head>


{% block body %}
<body class="{% block body_class %}{% endblock %}">
    {% block scripts %}{% endblock %}

    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="">Coro di S.Antonio</a>
            {% block navbar_apps %}
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'repertory:song_list' %}">{% translate "Repertory" %}</a>
                <a class="nav-link" href="{% url 'events:event_list' %}">{% translate "Events" %}</a>
            </div>
            {% endblock %}
            {% block navbar_auth %}
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <span class="navbar-text">{{ user.get_short_name }}</span>
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
            {% endblock %}
        </div>
    </nav>
    {% endblock %}
    <div class="container">
    {% block content %}{% endblock %}
    </div>
</body>
{% endblock %}
</html>

choir/web/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}
        <div class="hero-unit well">
        {% block banner %}
            <h1>Coro di S.Antonio</h1>
            <p></p>
            <p class="what_next">Vuoi dare un'occhiata al <a href="{% url repertory:song_list %}" class="btn btn-primary btn-large"><i class="icon-music icon-white"></i> Repertorio</a> ?</p>
        {% endblock %}
        </div>
{% endblock %}

choir/web/templates/site_base.html
{% extends "base.html" %}